# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout badges branch dedicated to storing badges only
      uses: actions/checkout@v2
      with:
        ref: badges
        path: badges
        
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B test --file pom.xml
      
    - name: Generate JaCoCo Badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v2
      with:
        badges-directory: badges
        generate-branches-badge: true
        generate-summary: true
        fail-if-coverage-less-than: 50
        fail-on-coverage-decrease: true

    - name: Log coverage percentage(if it changed)
      if: ${{ github.event_name == 'push' }}
      run: |
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
        echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"
    - name: Commit the badge (if it changed)
      if: ${{ github.event_name == 'push' }}
      run: |
      cd badges
      if [[ git status --porcelain *.svg *.json ]]; then
      git config --global user.name 'github-actions'
      git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
      git add *.svg *.json
      git commit -m "Autogenerated JaCoCo coverage badges" *.svg *.json
      git push
      fi
      #    - name: Commit and push the badge (if it changed)
      #      if: ${{ github.event_name == 'push' }}
      #      uses: EndBug/add-and-commit@v8.0.2
      #      with:
      #        default_author: github_actions
      #        message: 'commit badge'
      #        add: '*.svg'
    - name: Upload JaCoCo coverage report
      if: ${{ github.event_name == 'push' }}
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: target/site/jacoco/
